repos:
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: bash -c "source .venv/bin/activate" && jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace